version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: W14i05l77!
      MYSQL_DATABASE: db_washington
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "3306:3306"

  backend:
    container_name: backend_container
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: caddy:latest
    container_name: caddy_container
    ports:
      - "80:80"
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist/filmes-app:/usr/share/caddy/html # Altere para o diretório onde sua aplicação Angular está compilada
    depends_on:
      - backend
